-- 1. 대륙, 국가, 도시, 부서, 직무별 사원의 수, 사원들의 평균 급여를 조회하세요.
SELECT R.REGION_NAME
 	 , C.COUNTRY_NAME 
 	 , L.CITY 
 	 , D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE 
 	 , AVG(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID
 INNER JOIN REGIONS R
 	ON C.REGION_ID = R.REGION_ID
 GROUP BY R.REGION_NAME
 	 , C.COUNTRY_NAME 
 	 , L.CITY 
 	 , D.DEPARTMENT_NAME 
 	 , J.JOB_TITLE 
;
-- 2. 각 부서장 사원번호별 사원의 수를 조회하고 사원의 수로 오름차순 정렬하세요.
SELECT MANAGER_ID 
	 , COUNT(EMPLOYEE_ID) AS CNT
  FROM EMPLOYEES E
 WHERE E.MANAGER_ID IN (SELECT DISTINCT MANAGER_ID 
 						  FROM DEPARTMENTS)
 GROUP BY MANAGER_ID 
 ORDER BY CNT
;
-- 3. 직무가 받을 수 있는 평균 급여(MAX_SALARY, MIN_SALARY)보다 많은 급여를 받는 사원들을 직무별 사원의 수로 조회하세요.
SELECT *
  FROM EMPLOYEES E
 INNER JOIN (SELECT JOB_ID 
 				  , MAX(SALARY)
 				  , MIN(SALARY)
 			   FROM EMPLOYEES
 			  GROUP BY JOB_ID) J
    ON E.JOB_ID = J.JOB_ID 
 WHERE 
; 			  
-- 4. 모든 부서장들의 부하직원들을 계층 조회하세요.