-- 1. 현재 시간을 조회한다.
SELECT SYSDATE
  FROM DUAL -- is Dummy Table.
;
-- 2. 현재 시간을 "연-월-일" 포멧으로 조회한다.
--SELECT CAST (SYSDATE AS DATE)
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
  FROM DUAL
;
-- 3. 한 시간 전 시간을 "시:분:초" 포멧으로 조회한다.
--SELECT TO_CHAR(SYSDATE, 'HH:MI:SS')
SELECT TO_CHAR(SYSDATE - 1/24, 'HH24:MI:SS')
  FROM DUAL
;
-- 4. EMPLOYEES 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
;
-- 5. DEPARTMENTS 테이블의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
	 , DEPARTMENT_NAME 
	 , MANAGER_ID 
	 , LOCATION_ID 
  FROM DEPARTMENTS
;
-- 6. JOBS 테이블의 모든 정보를 조회한다.
SELECT JOB_ID 
     , JOB_TITLE 
     , MIN_SALARY 
     , MAX_SALARY 
  FROM JOBS
;
-- 7. LOCATIONS 테이블의 모든 정보를 조회한다.
SELECT LOCATION_ID 
	 , STREET_ADDRESS 
	 , POSTAL_CODE 
	 , CITY 
	 , STATE_PROVINCE 
	 , COUNTRY_ID 
  FROM LOCATIONS
;
-- 8. COUNTRIES 테이블의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
     , COUNTRY_NAME 
     , REGION_ID 
  FROM COUNTRIES
;
-- 9. REGIONS 테이블의 모든 정보를 조회한다.
SELECT REGION_ID 
     , REGION_NAME 
  FROM REGIONS
;
-- 10. JOB_HISTORY 테이블의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID 
     , START_DATE 
     , END_DATE 
     , JOB_ID 
     , DEPARTMENT_ID 
  FROM JOB_HISTORY
;
-- 11. 상사사원번호를 중복없이 조회한다.
SELECT COUNT(MANAGER_ID), COUNT(DISTINCT MANAGER_ID)   
  FROM EMPLOYEES
;
SELECT DISTINCT MANAGER_ID  
  FROM EMPLOYEES
;
-- 12. 90번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 90
;
-- 13. 90번, 100번 부서에서 근무하는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (90 , 100)
;
-- 14. 100번 상사의 직속 부하직원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE MANAGER_ID = 100
;
-- 15. 111번 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 111
;
-- 16. 직무 아이디가 AD_VP 인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE JOB_ID = 'AD_VP'
;
-- 17. 급여가 7000 이상인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY >= 700
;
-- 18. 직무 아이디가 'PU_CLERK'인 사원 중 급여가 3000 이상인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE JOB_ID = 'PU_CLERK'
   AND SALARY >= 3000
;
-- 19. 급여가 2500, 3500, 7000 이 아니며 직업이 SA_REP 이나 ST_CLERK 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY NOT IN (2500,3500,7000)
   AND JOB_ID IN ('SA_REP', 'ST_CLERK')
;
-- 20. 커미션을 안받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NULL 
;
-- 21. 커미션을 받는 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT IS NOT NULL 
;
-- 21. 이름의 첫 글자가 'D' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE 'D%' -- LIKE는 실무에서 절대 사용하지 않음.
;
-- 22. 성의 마지막 글자가 'a' 인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE '%a'
;
-- 23. 전화번호에 '.124.'이 포함된 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '%.124.%'
;
-- 24. 이름이 4글자인 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '____'
;
-- 25. 이름이나 성에 'A' 혹은 'a' 가 포함된 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%A%'
    OR FIRST_NAME LIKE '%a%'
    OR LAST_NAME LIKE '%A%'
    OR LAST_NAME LIKE '%a%'
-- WHERE LOWER(FIRST_NAME || LAST_NAME) LIKE '%a%' -- DB CPU 사용량 증가
;
-- 26. 국가명이 6자리인 국가의 모든 정보를 조회한다.
SELECT COUNTRY_ID 
     , COUNTRY_NAME 
     , REGION_ID 
  FROM COUNTRIES
 WHERE COUNTRY_NAME LIKE '______'
;
-- 27. '20230222' 문자 데이터를 날짜로 변환해 조회한다.(DUAL)
SELECT TO_DATE('20230222', 'YYYY-MM-DD') 
  FROM DUAL
;
-- 28. '20230222' 문자 데이터를 'YYYY-MM' 으로 변환해 조회한다.(DUAL)
SELECT TO_CHAR(TO_DATE('20230222', 'YYYY-MM-DD'),'YYYY-MM')
  FROM DUAL
;
-- 29. '20230222130140' 문자 데이터를 'YYYY-MM-DD HH24:MI:SS' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE('20230222130140','YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS')
  FROM DUAL
;
-- 30. '20230222' 날짜의 열흘 후의 날짜를 'YYYY-MM-DD' 으로 변환해 조회한다. (DUAL)
SELECT TO_CHAR(TO_DATE('20230222','YYYY-MM-DD') + 10, 'YYYY-MM-DD')
  FROM DUAL
;
-- 31. 직원의 입사일자를 '연-월-일' 형태로 조회한다.
SELECT TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') 
  FROM EMPLOYEES
;
-- 32. 2005년 09월에 입사한 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
--     , TO_CHAR(HIRE_DATE,'YYYY-MM') AS a
  FROM EMPLOYEES
-- WHERE TO_CHAR(HIRE_DATE,'YYYY-MM') = '2005-09'
-- WHERE HIRE_DATE BETWEEN TO_DATE('2005-09-01','YYYY-MM-DD') AND TO_DATE('2005-10-01','YYYY-MM-DD')-1  
 WHERE HIRE_DATE >= TO_DATE('2005-09-01','YYYY-MM-DD') 
   AND HIRE_DATE < TO_DATE('2005-10-01','YYYY-MM-DD')   
;
-- 33. 현재 시간으로부터 20년 전 보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE > ADD_MONTHS(SYSDATE, -20*12)
;
-- 34. 사원들의 정보 중 입사연도, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE,'YYYY') 
     , LAST_NAME  
     , FIRST_NAME 
  FROM EMPLOYEES
;
-- 35. 사원들의 정보 중 입사연도, 입사월, 이름, 성만 조회한다.
SELECT TO_CHAR(HIRE_DATE,'YYYY')
     , TO_CHAR(HIRE_DATE,'MM')
     , LAST_NAME  
     , FIRST_NAME 
  FROM EMPLOYEES
;
-- 36. MOD 함수를 통해 사원번호가 홀수면 남자, 짝수면 여자 로 구분해 조회한다. MOD(값, 나눌값)
-- 37. 사원 모든 정보 중 이메일만 모두 소문자로 변경하여 조회한다.
-- 38. 사원의 급여를 TRUNC(소수점 버림) 함수를 사용해 100 단위는 버린채 다음과 같이 조회한다. 예> 3700 -> 3000, 12700 -> 12000
-- 39. 100단위를 버린 사원의 급여 별 사원의 수를 조회한다.
-- 40. 모든 사원들의 이름을 10자리로 맞추어 조회한다.
-- 41. 사원의 이름과 성을 이용해 EMAIL과 같은 값으로 만들어 조회한다.
-- 42. 모든 사원들의 이름을 10자리로 변환해 조회한다. 예> 이름 => "        이름"
-- 43. 모든 사원들의 성을 10자리로 변환해 조회한다. 예> 성 => "성         "
-- 44. 모든 사원들의 모든 정보를 조회한다. 단, 커미션을 받는 사원은 "커미션여부" 컬럼에 "Y"를, 아닌 경우 "N"으로 조회한다.
-- 45. 사원의 모든 정보를 조회한다. 
--      사원의 급여가 5000 이하이면 "사원", 7000 이하이면 "대리", 9000 이하이면 "과장", 그 외에는 임원 으로 조회한다.
-- 46. 모든 사원들의 모든 정보를 급여 오름차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 ORDER BY SALARY ASC 
;
-- 47. 모든 사원들의 모든 정보를 이름 내림차순 정렬하여 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 ORDER BY FIRST_NAME DESC 
;
-- 48. 모든 사원들의 모든 정보를 직무 오름차순, 급여 내림차순으로 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 ORDER BY JOB_ID ASC
     , SALARY DESC 
;
-- 49. 가장 늦게 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MAX( HIRE_DATE )
  FROM EMPLOYEES)
;
-- 50. 가장 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE = (SELECT MIN( HIRE_DATE )
  FROM EMPLOYEES)
;
-- 51. 사내의 최고급여과 최저급여의 차이를 조회한다.
SELECT MAX( SALARY ) - MIN( SALARY )
  FROM EMPLOYEES
;
-- 52. 102번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT( EMPLOYEE_ID )
  FROM EMPLOYEES
 WHERE MANAGER_ID = 102
;
-- 53. 113번 직원의 직속 부하직원의 수를 조회한다.
SELECT COUNT( EMPLOYEE_ID )
  FROM EMPLOYEES
 WHERE MANAGER_ID = 113
;
-- 54. 'SA_REP' 직무인 직원 중 가장 높은 급여과 가장 낮은 급여를 조회한다.
SELECT MAX( SALARY )
     , MIN( SALARY )
  FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP'
;
-- 55. 부서아이디별 평균 급여를 조회한다.
SELECT DEPARTMENT_ID 
     , AVG( SALARY )
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID  
 ORDER BY DEPARTMENT_ID  
;
-- 56. 직무아이디별 평균 급여, 최고급여, 최저급여를 조회한다.
SELECT JOB_ID
     , AVG( SALARY )
     , MAX( SALARY )
     , MIN( SALARY )
  FROM EMPLOYEES
 GROUP BY JOB_ID
 ORDER BY JOB_ID 
;
-- 57. 직무아이디별 사원의 수를 조회한다.
SELECT JOB_ID
     , COUNT( EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY JOB_ID
 ORDER BY JOB_ID 
;
-- 58. 상사아이디별 부하직원의 수를 조회한다. 단, 부하직원이 2명 이하인 경우는 제외한다.
SELECT MANAGER_ID
     , COUNT( EMPLOYEE_ID )
  FROM EMPLOYEES
 GROUP BY MANAGER_ID  
HAVING COUNT( EMPLOYEE_ID ) > 2
 ORDER BY COUNT( EMPLOYEE_ID )
; -- ORDER BY는 항상 마지막에
-- 59. 부서번호별 현재 시간으로부터 15년 전 보다 일찍 입사한 사원의 수를 조회한다.
SELECT DEPARTMENT_ID
     , COUNT( EMPLOYEE_ID )
  FROM EMPLOYEES
 WHERE HIRE_DATE < ADD_MONTHS(SYSDATE, -15*12) 
 GROUP BY DEPARTMENT_ID 
 ORDER BY DEPARTMENT_ID  
;
-- 60. 커미션을 안받는 사원이 근무하는 도시를 조회한다.
SELECT CITY 
  FROM LOCATIONS
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID 
 						 FROM DEPARTMENTS
						WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
												  FROM EMPLOYEES
												 WHERE COMMISSION_PCT IS NULL))
;
-- 61. 회사 전체의 평균 급여보다 많이 받는 사원들 중 이름에 'u' 가 포함된 사원과 동일한 부서에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
   				   FROM EMPLOYEES)
   AND DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
  						   FROM EMPLOYEES
 						  WHERE FIRST_NAME LIKE '%u%')
;
-- 62. 이름이 'Renske' 인 사원의 급여과 같은 급여를 받는 사원의 모든 정보를 조회한다. 단, 'Renske' 사원은 조회에서 제외한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY = (SELECT SALARY
                   FROM EMPLOYEES
                  WHERE FIRST_NAME = 'Renske')
   AND FIRST_NAME != 'Renske'
;
-- 63. 평균 급여보다 많이 받는 사원들의 사원번호, 이름, 성, 급여를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , SALARY 
  FROM EMPLOYEES
 WHERE SALARY > (SELECT AVG(SALARY)
   				   FROM EMPLOYEES)
;
-- 64. 평균 급여보다 적게 받는 사원들의 사원번호, 급여, 부서번호를 조회한다.
SELECT EMPLOYEE_ID
     , SALARY 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE SALARY < (SELECT AVG(SALARY)
   				   FROM EMPLOYEES)
;
-- 65. 가장 많은 급여를 받는 사원의 사원번호, 이름, 급여를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , SALARY  
  FROM EMPLOYEES
 WHERE SALARY = (SELECT MAX(SALARY)
   				   FROM EMPLOYEES)
;
-- 66. 자신의 상사보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID
  FROM EMPLOYEES E 
 INNER JOIN (SELECT EMPLOYEE_ID
			      , SALARY
	           FROM EMPLOYEES) EM
  	ON E.MANAGER_ID = EM.EMPLOYEE_ID 
 WHERE E.SALARY > EM.SALARY 
;
SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME 
     , E1.LAST_NAME 
     , E1.EMAIL 
     , E1.PHONE_NUMBER 
     , E1.HIRE_DATE 
     , E1.JOB_ID 
     , E1.SALARY 
     , E1.COMMISSION_PCT 
     , E1.MANAGER_ID 
     , E1.DEPARTMENT_ID
  FROM EMPLOYEES E1
 WHERE E1.SALARY > (SELECT E2.SALARY  
	    			  FROM EMPLOYEES E2
	    			 WHERE E2.EMPLOYEE_ID = E1.MANAGER_ID)
;
-- 67. 자신의 상사보다 더 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID
  FROM EMPLOYEES E 
 INNER JOIN (SELECT EMPLOYEE_ID
				  , HIRE_DATE
  			   FROM EMPLOYEES) EM
  	ON E.MANAGER_ID = EM.EMPLOYEE_ID 
 WHERE E.HIRE_DATE < EM.HIRE_DATE 
;
SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME 
     , E1.LAST_NAME 
     , E1.EMAIL 
     , E1.PHONE_NUMBER 
     , E1.HIRE_DATE 
     , E1.JOB_ID 
     , E1.SALARY 
     , E1.COMMISSION_PCT 
     , E1.MANAGER_ID 
     , E1.DEPARTMENT_ID
  FROM EMPLOYEES E1
 WHERE E1.HIRE_DATE < (SELECT E2.HIRE_DATE 
 		    			 FROM EMPLOYEES E2
 		    			WHERE E2.EMPLOYEE_ID = E1.MANAGER_ID)
;
-- 68. 가장 많은 커미션을 받는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE COMMISSION_PCT = (SELECT MAX(COMMISSION_PCT)
   				           FROM EMPLOYEES)
;
-- 69. 가장 적은 커미션을 받는 사원의 급여과 커미션을 조회한다.
SELECT SALARY 
     , COMMISSION_PCT
  FROM EMPLOYEES
 WHERE COMMISSION_PCT = (SELECT MIN(COMMISSION_PCT)
   				           FROM EMPLOYEES)
;
-- 70. 사원이 속한 부서의 평균급여보다 적게 받는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN (SELECT DEPARTMENT_ID 
 				  , AVG(SALARY) AS DEPT_AVG_SAL
  			   FROM EMPLOYEES
  			  GROUP BY DEPARTMENT_ID) D
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
   AND E.SALARY < D.DEPT_AVG_SAL 
;
SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME 
     , E1.LAST_NAME 
     , E1.EMAIL 
     , E1.PHONE_NUMBER 
     , E1.HIRE_DATE 
     , E1.JOB_ID 
     , E1.SALARY 
     , E1.COMMISSION_PCT 
     , E1.MANAGER_ID 
     , E1.DEPARTMENT_ID
  FROM EMPLOYEES E1
 WHERE E1.SALARY < (SELECT AVG(E2.SALARY)
 					  FROM EMPLOYEES E2
 					 WHERE E2.DEPARTMENT_ID = E1.DEPARTMENT_ID)
;
-- 71. 50번 부서의 부서장의 이름, 성, 급여를 조회한다.
SELECT FIRST_NAME 
     , LAST_NAME 
     , SALARY 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = (SELECT MANAGER_ID 
 						FROM DEPARTMENTS
 					   WHERE DEPARTMENT_ID = 50)
;
-- 72. 사원이 없는 부서명을 조회한다.
SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID NOT IN (SELECT DISTINCT DEPARTMENT_ID 
                               FROM EMPLOYEES
                              WHERE DEPARTMENT_ID IS NOT NULL)
;-- NOT IN 사용 시에는 NULL data 제거 후에 사용해야함.
-- 73. 직무가 변경된 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID IN (SELECT DISTINCT EMPLOYEE_ID 
                         FROM JOB_HISTORY)
;
-- 74. 직무가 변경된적 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (SELECT DISTINCT EMPLOYEE_ID 
                             FROM JOB_HISTORY)
;
-- 75. 직무가 가장 많이 변경된 부서의 이름을 조회한다.
-- 1
SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                           FROM (SELECT DEPARTMENT_ID
                                      , COUNT(EMPLOYEE_ID) AS CNT
								   FROM JOB_HISTORY
								  GROUP BY DEPARTMENT_ID
								 HAVING COUNT(EMPLOYEE_ID) = (SELECT MAX(CNT)
 																FROM (SELECT COUNT(EMPLOYEE_ID) AS CNT
 		 																FROM JOB_HISTORY
       																   GROUP BY DEPARTMENT_ID))))
;
-- 2
WITH T AS (SELECT D.DEPARTMENT_ID
				, D.DEPARTMENT_NAME 
                , COUNT(J.EMPLOYEE_ID) AS CNT
      		 FROM JOB_HISTORY J
      		INNER JOIN DEPARTMENTS D
      		   ON J.DEPARTMENT_ID  = D.DEPARTMENT_ID 
            GROUP BY D.DEPARTMENT_ID)
SELECT DEPARTMENT_NAME 
  FROM T
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
  						   FROM T
  						  WHERE CNT = (SELECT MAX(CNT)
  						  				 FROM T))
--SELECT DEPARTMENT_NAME 
--  FROM DEPARTMENTS
-- WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
--  						   FROM T
--  						  WHERE CNT = (SELECT MAX(CNT)
--  						  				 FROM T))
;
-- 3 
SELECT DEPARTMENT_NAME 
  FROM DEPARTMENTS
 WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
						  FROM (SELECT D.DEPARTMENT_ID
									 , COUNT(D.DEPARTMENT_ID) AS CNT
								  FROM JOB_HISTORY JH
								 INNER JOIN DEPARTMENTS D
									ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
								 GROUP BY D.DEPARTMENT_ID
								 ORDER BY CNT DESC)
						 WHERE ROWNUM = 1)
;
-- 76. 근무중인 사원이 없는 도시를 조회한다.
SELECT CITY 
  FROM LOCATIONS
 WHERE LOCATION_ID NOT IN (SELECT DISTINCT LOCATION_ID 
	 						 FROM DEPARTMENTS
	 						WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
	 												  FROM EMPLOYEES))
 						
;
-- 77. 급여가 7000 에서 12000 사이인 사원이 근무중인 도시를 조회한다.
SELECT CITY  
  FROM LOCATIONS 
 WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID 
 						 FROM DEPARTMENTS 
 						WHERE DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID 
 												  FROM EMPLOYEES
 												 WHERE SALARY >= 7000
 												   AND SALARY <= 12000))
;
-- 78. 'Seattle' 에서 근무중인 사원의 직무명을 중복없이 조회한다.
SELECT JOB_TITLE 
  FROM JOBS
 WHERE JOB_ID IN (SELECT DISTINCT JOB_ID 
 					FROM EMPLOYEES
 				   WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
 				   							 FROM DEPARTMENTS
 				   							WHERE LOCATION_ID = (SELECT LOCATION_ID 
 				   												   FROM LOCATIONS
 				   												  WHERE CITY = 'Seattle')))
;
-- 79. 부서가 없는 국가명을 조회한다.
SELECT COUNTRY_NAME 
  FROM COUNTRIES
 WHERE COUNTRY_ID NOT IN (SELECT DISTINCT COUNTRY_ID 
						    FROM LOCATIONS
						   WHERE LOCATION_ID IN (SELECT DISTINCT LOCATION_ID 
												   FROM DEPARTMENTS))
;
-- 80. 'Europe' 에서 근무중인 사원들의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
						   FROM DEPARTMENTS
						  WHERE LOCATION_ID IN (SELECT LOCATION_ID 
												  FROM LOCATIONS
												 WHERE COUNTRY_ID IN (SELECT COUNTRY_ID 
																	    FROM COUNTRIES
																	   WHERE REGION_ID = (SELECT REGION_ID 
																						    FROM REGIONS 
																						   WHERE REGION_NAME = 'Europe'))))
;
-- 81. 'Seattle' 에서 근무중인 사원의 이름, 성, 급여, 부서명 을 조회한다.
SELECT E.FIRST_NAME 
     , E.LAST_NAME 
     , E.SALARY 
     , D.DEPARTMENT_NAME
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE LOCATION_ID = (SELECT LOCATION_ID
						FROM LOCATIONS
					   WHERE CITY = 'Seattle')
;
-- 82. 'Seattle' 에서 근무하지 않는 모든 사원의 이름, 성, 급여, 부서명, 도시를 조회한다.
SELECT E.FIRST_NAME 
     , E.LAST_NAME 
     , E.SALARY 
     , D.DEPARTMENT_NAME
     , L.CITY 
  FROM EMPLOYEES E 
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
 WHERE L.CITY != 'Seattle'
;
-- 83. 모든 사원들의 이름, 성, 급여, 부서명을 부서번호로 내림차순 정렬하여 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 ORDER BY D.DEPARTMENT_ID DESC
;
-- 84. 2007년에 직무가 변경된 사원들의 현재 직무명, 부서명, 사원번호, 이름, 성을 조회한다.
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.EMPLOYEE_ID IN (SELECT DISTINCT EMPLOYEE_ID 
 						   FROM JOB_HISTORY
 						  WHERE START_DATE >= TO_DATE('2007-01-01')
 						    AND START_DATE <= TO_DATE('2007-12-31'))
;
-- 85. 부서장이 없는 부서명 중 첫 글자가 'C' 로 시작하는 부서명을 조회한다.
SELECT DEPARTMENT_NAME  
  FROM DEPARTMENTS
 WHERE MANAGER_ID IS NULL
   AND DEPARTMENT_NAME LIKE 'C%'
;
-- 86. 지역변호가 1000 ~ 1999 사이인 지역내 부서의 모든 정보를 조회한다.
SELECT DEPARTMENT_ID 
     , DEPARTMENT_NAME 
     , MANAGER_ID 
     , LOCATION_ID 
  FROM DEPARTMENTS
 WHERE LOCATION_ID >= 1000
   AND LOCATION_ID <= 1999
;
-- 87. 국가 아이디가 'C'로 시작하는 국가의 지역을 모두 조회한다.
SELECT LOCATION_ID 
     , STREET_ADDRESS 
     , POSTAL_CODE 
     , CITY 
     , STATE_PROVINCE 
     , COUNTRY_ID 
  FROM LOCATIONS
 WHERE COUNTRY_ID LIKE 'C%'
;
-- 88. 109번 사원의 입사일 부터 1년 동안 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE >= (SELECT HIRE_DATE
                       FROM EMPLOYEES
                      WHERE EMPLOYEE_ID = 109)
   AND HIRE_DATE <= ADD_MONTHS((SELECT HIRE_DATE
                      			  FROM EMPLOYEES
                    		     WHERE EMPLOYEE_ID = 109), 12) 
;
-- 89. 가장 먼저 입사한 사원의 입사일로부터 2년 동안 입사한사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE >= (SELECT MIN(HIRE_DATE)
                       FROM EMPLOYEES)
   AND HIRE_DATE <= ADD_MONTHS((SELECT MIN(HIRE_DATE)
                       			  FROM EMPLOYEES), 2*12) 
;
-- 90. 가장 늦게 입사한 사원의 입사일의 1년 전보다 일찍 입사한 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE HIRE_DATE <= ADD_MONTHS((SELECT MAX(HIRE_DATE)
                       			  FROM EMPLOYEES), -12)
;
-- 91. 사원들이 근무하는 부서명, 이름, 성을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
;
-- 92. 우편번호가 5자리인 도시에서 근무하는 사원명, 부서명, 도시명, 우편번호를 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
	 , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
   AND L.POSTAL_CODE LIKE ('_____')
;
-- 93. 부서장이 있는 부서명 중 첫 글자가 'S' 로 시작하는 부서에서 근무중인 사원의 이름과 직무명, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
   AND D.MANAGER_ID IS NOT NULL 
   AND D.DEPARTMENT_NAME LIKE 'S%'
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
;
-- 94. 90, 60, 100번 부서에서 근무중인 사원의 이름, 성, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , E.LAST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
   AND D.DEPARTMENT_ID IN (90, 60, 100)
;
-- 95. 부서명이 5글자 미만인 부서에서 근무중인 사원의 이름, 부서명을 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
   AND D.DEPARTMENT_NAME NOT LIKE '_____%'
;
-- 96. 도시명에 띄어쓰기 " " 가 포함된 도시에서 근무중인 사원들의 부서명, 도시명, 사원명을 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , L.CITY 
	 , E.FIRST_NAME 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
   AND L.CITY LIKE '% %'
;
-- 97. 우편번호에 공백이 없는 도시에서 근무하는 사원의 이름, 부서명, 우편번호를 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , L.POSTAL_CODE 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
   AND L.POSTAL_CODE NOT LIKE '% %'
;
-- 98. "주"가 없는 도시에서 근무하는 사원의 이름, 도시를 조회한다.
SELECT E.FIRST_NAME 
	 , L.CITY 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
   AND L.STATE_PROVINCE IS NULL
;
-- 99. 사원들의 사원번호, 이름, 성, 상사의 사원번호, 상사의 이름, 상사의 성을 조회한다.
SELECT E.EMPLOYEE_ID 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , EM.EMPLOYEE_ID 
	 , EM.FIRST_NAME 
	 , EM.LAST_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES EM
 	ON E.MANAGER_ID = EM.EMPLOYEE_ID
;
-- 100. 직무가 변경된 사원의 이름과 과거 직무명과 현재 직무명을 조회한다.
SELECT E.FIRST_NAME 
	 , J2.JOB_TITLE 
	 , J1.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOB_HISTORY JH
 	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
 INNER JOIN JOBS J1
 	ON E.JOB_ID = J1.JOB_ID 
 INNER JOIN JOBS J2
 	ON JH.JOB_ID = J2.JOB_ID 
;
-- 101. 가장 적은 급여를 받는 사원의 부서명, 이름, 성, 급여, 부서장사원번호를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , E.FIRST_NAME 
	 , E.LAST_NAME 
	 , E.SALARY 
	 , E.MANAGER_ID 
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.SALARY = (SELECT MIN(SALARY)
 					 FROM EMPLOYEES)
;
-- 102. 부서명별 사원의 수를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
;
-- 103. 대륙명별 사원의 수를 조회한다.
SELECT R.REGION_NAME 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
 	ON C.REGION_ID = R.REGION_ID 
 GROUP BY R.REGION_NAME 
 ORDER BY R.REGION_NAME ASC
;
-- 104. 직무명별 최소급여를 조회한다.
SELECT J.JOB_TITLE 
	 , MIN(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID  
 GROUP BY J.JOB_TITLE  
 ORDER BY J.JOB_TITLE ASC
;
-- 105. 부서명별 최대급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , MAX(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY D.DEPARTMENT_NAME ASC
;
-- 106. 직무명별 평균급여를 평균급여순으로 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE 
	 , AVG(E.SALARY) AS AVG_SAL
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID  
 GROUP BY J.JOB_TITLE  
 ORDER BY AVG_SAL ASC
;
-- 107. 부서명별 평균급여를 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , AVG(E.SALARY) AS AVG_SAL
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY AVG_SAL DESC
;
-- 109. 부서명별 급여의 합을 내림차순 정렬하여 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , SUM(E.SALARY) AS SUM_SAL
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
 ORDER BY SUM_SAL DESC
;
-- 110. 직무명별 사원의 수를 오름차순 정렬하여 조회한다.
SELECT J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID ) AS CNT_SAL
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID  
 GROUP BY J.JOB_TITLE  
 ORDER BY CNT_SAL ASC
;
-- 111. 직무명, 부서명 별 사원 수, 평균급여를 조회한다.
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID) AS CNT_SAL
	 , AVG(E.SALARY) AS AVG_SAL
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID  
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 GROUP BY J.JOB_TITLE
     , D.DEPARTMENT_NAME
 ORDER BY CNT_SAL DESC
     , AVG_SAL DESC
;
-- 112. 도시별 사원 수를 조회한다.
SELECT L.CITY 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY L.CITY 
 ORDER BY L.CITY ASC
;
-- 113. 국가별 사원 수, 최대급여, 최소급여를 조회한다.
SELECT C.COUNTRY_NAME
	 , COUNT(E.EMPLOYEE_ID)
	 , MAX(E.SALARY)
	 , MIN(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 GROUP BY C.COUNTRY_NAME 
 ORDER BY C.COUNTRY_NAME ASC
;
-- 114. 국가별로 급여가 5000 이상인 사원의 수를 조회한다.
SELECT C.COUNTRY_NAME
	 , COUNT(E.EMPLOYEE_ID)
--  FROM EMPLOYEES E
  FROM (SELECT EMPLOYEE_ID 
  		  FROM EMPLOYEES
  		 WHERE SALARY >= 5000) E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
-- WHERE E.SALARY >= 5000
 GROUP BY C.COUNTRY_NAME 
 ORDER BY C.COUNTRY_NAME ASC
;
-- 115. 부서명, 직무명 별 평균 급여를 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , J.JOB_TITLE 
	 , AVG(E.SALARY)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME, J.JOB_TITLE
;
-- 116. 도시명, 직무명 별 사원의 수를 조회한다.
SELECT L.CITY 
	 , J.JOB_TITLE 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
 INNER JOIN JOBS J
    ON E.JOB_ID = J.JOB_ID 
 GROUP BY L.CITY
     , J.JOB_TITLE 
 ORDER BY L.CITY ASC
     , J.JOB_TITLE ASC
;
-- 117. 부서명, 직무명 별 평균 급여 중 가장 작은 평균급여를 받는 부서명, 직무명을 조회한다.
-- 1
SELECT D.DEPARTMENT_NAME
	 , J.JOB_TITLE
	 , AVG(E.SALARY) AS AVG_SAL
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
 GROUP BY D.DEPARTMENT_NAME
     , J.JOB_TITLE
HAVING AVG(E.SALARY) = (SELECT MIN(AVG_SAL)
 						  FROM (SELECT AVG(E.SALARY) AS AVG_SAL
						    	  FROM EMPLOYEES E
						   		 INNER JOIN DEPARTMENTS D
						 	  		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
						   		 INNER JOIN JOBS J
						 	  		ON E.JOB_ID = J.JOB_ID
						   		 GROUP BY D.DEPARTMENT_NAME
						   		     , J.JOB_TITLE))
;
-- 2
WITH T AS (SELECT D.DEPARTMENT_NAME
				, J.JOB_TITLE
				, AVG(E.SALARY) AS AVG_SAL
			 FROM EMPLOYEES E
			INNER JOIN DEPARTMENTS D
			   ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
			INNER JOIN JOBS J
			   ON E.JOB_ID = J.JOB_ID
			GROUP BY D.DEPARTMENT_NAME
				   , J.JOB_TITLE)
SELECT DEPARTMENT_NAME
	 , JOB_TITLE 
	 , AVG_SAL 
  FROM T
 WHERE AVG_SAL = (SELECT MIN(AVG_SAL)
 					FROM T)
;
-- 3
SELECT DEPARTMENT_NAME
	 , JOB_TITLE
  FROM (SELECT D.DEPARTMENT_NAME
			 , J.JOB_TITLE
			 , AVG(E.SALARY) AS AVG_SAL
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		 INNER JOIN JOBS J
		    ON E.JOB_ID = J.JOB_ID
		 GROUP BY D.DEPARTMENT_NAME
			 , J.JOB_TITLE
		 ORDER BY AVG_SAL ASC)
 WHERE ROWNUM = 1
;
-- 118. 대륙명별 사원 수를 대륙명으로 오름차순 정렬하여 조회한다.
SELECT R.REGION_NAME 
	 , COUNT(E.EMPLOYEE_ID)
  FROM EMPLOYEES E
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 INNER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID 
 INNER JOIN COUNTRIES C
 	ON L.COUNTRY_ID = C.COUNTRY_ID 
 INNER JOIN REGIONS R
 	ON C.REGION_ID = R.REGION_ID 
 GROUP BY R.REGION_NAME 
 ORDER BY R.REGION_NAME ASC
;
-- 119. 수행중인 직무의 최대급여(JOBS.MAX_SALARY)보다 더 많은 급여를 받는 사원의 모든 정보를 조회한다.
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON J.JOB_ID = E.JOB_ID 
 WHERE E.SALARY > J.MAX_SALARY 
;
SELECT E.EMPLOYEE_ID
     , E.FIRST_NAME 
     , E.LAST_NAME 
     , E.EMAIL 
     , E.PHONE_NUMBER 
     , E.HIRE_DATE 
     , E.JOB_ID 
     , E.SALARY 
     , E.COMMISSION_PCT 
     , E.MANAGER_ID 
     , E.DEPARTMENT_ID
  FROM EMPLOYEES E
 WHERE E.SALARY > (SELECT J.MAX_SALARY
 					 FROM JOBS J
 					WHERE J.JOB_ID = E.JOB_ID)
;
-- 120. 입사연도별 최소급여를 조회한다.
SELECT HIRE_YEAR
	 , MIN(SALARY)
  FROM (SELECT TO_CHAR(HIRE_DATE,'YYYY') AS HIRE_YEAR
  			 , SALARY 
  		  FROM EMPLOYEES
  		 )
 GROUP BY HIRE_YEAR
 ORDER BY HIRE_YEAR ASC
;
-- 121. 사원 이름의 글자수 별 사원의 수를 조회한다.
SELECT LEN_FN
	 , COUNT(EMPLOYEE_ID)
  FROM (SELECT LENGTH(FIRST_NAME) AS LEN_FN
  			 , EMPLOYEE_ID
  		  FROM EMPLOYEES)
 GROUP BY LEN_FN 
 ORDER BY LEN_FN ASC 
;
-- 122. 사원 성의 글자수 별 사원의 수를 조회한다.
SELECT LEN_LN
	 , COUNT(EMPLOYEE_ID)
  FROM (SELECT LENGTH(LAST_NAME) AS LEN_LN
  			 , EMPLOYEE_ID
  		  FROM EMPLOYEES)
 GROUP BY LEN_LN 
 ORDER BY LEN_LN ASC 
;
-- 123. 커미션을 포함한 급여가 10000 이상인 사원의 모든 정보를 조회한다.
--SELECT E1.EMPLOYEE_ID
--     , E1.FIRST_NAME 
--     , E1.LAST_NAME 
--     , E1.EMAIL 
--     , E1.PHONE_NUMBER 
--     , E1.HIRE_DATE 
--     , E1.JOB_ID 
--     , E1.SALARY 
--     , E1.COMMISSION_PCT 
--     , E1.MANAGER_ID 
--     , E1.DEPARTMENT_ID 
--  FROM EMPLOYEES E1
-- OUTER RIGHT JOIN (SELECT EMPLOYEE_ID 
-- 				        , SALARY * (1+COMMISSION_PCT) AS TOTAL_SAL
--                     FROM EMPLOYEES
--                    WHERE SALARY * (1+COMMISSION_PCT) >= 10000) E2
--    ON E1.EMPLOYEE_ID = E2.EMPLOYEE_ID 
--;
--SELECT EMPLOYEE_ID 
-- 				        , SALARY * COMMISSION_PCT AS TOTAL_SAL
--                     FROM EMPLOYEES;
-- 124. 국가 아이디의 첫 글자와 국가명의 첫 글자가 다른 모든 국가를 조회한다.
-- 125. 이름의 첫 번째 글자별 평균급여를 조회한다.


-- 126. 많은 급여를 받는 10명을 조회한다.
SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME 
     , E1.LAST_NAME 
     , E1.EMAIL 
     , E1.PHONE_NUMBER 
     , E1.HIRE_DATE 
     , E1.JOB_ID 
     , E1.SALARY 
     , E1.COMMISSION_PCT 
     , E1.MANAGER_ID 
     , E1.DEPARTMENT_ID 
     , E2.RNUM 
  FROM EMPLOYEES E1
 RIGHT OUTER JOIN (SELECT EMPLOYEE_ID 
						, ROWNUM AS RNUM
					 FROM (SELECT EMPLOYEE_ID 
					 		 FROM EMPLOYEES
					 	    ORDER BY SALARY DESC)
					WHERE ROWNUM <= 10) E2
	ON E2.EMPLOYEE_ID = E1.EMPLOYEE_ID 
;

-- 127. 많은 급여를 받는 사원 중 11번 째 부터 20번째를 조회한다.
SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME 
     , E1.LAST_NAME 
     , E1.EMAIL 
     , E1.PHONE_NUMBER 
     , E1.HIRE_DATE 
     , E1.JOB_ID 
     , E1.SALARY 
     , E1.COMMISSION_PCT 
     , E1.MANAGER_ID 
     , E1.DEPARTMENT_ID 
     , E2.RNUM 
  FROM EMPLOYEES E1
 RIGHT OUTER JOIN (SELECT EMPLOYEE_ID
 						, RNUM 
 					 FROM (SELECT EMPLOYEE_ID 
								, ROWNUM AS RNUM
							 FROM (SELECT EMPLOYEE_ID 
							 		 FROM EMPLOYEES
							 	    ORDER BY SALARY DESC)
							WHERE ROWNUM <= 20)
					WHERE RNUM >= 11) E2
	ON E2.EMPLOYEE_ID = E1.EMPLOYEE_ID 
;
-- 128. 가장 적은 급여를 받는 중 90번 째 부터 100번째를 조회한다.
SELECT E1.EMPLOYEE_ID
     , E1.FIRST_NAME 
     , E1.LAST_NAME 
     , E1.EMAIL 
     , E1.PHONE_NUMBER 
     , E1.HIRE_DATE 
     , E1.JOB_ID 
     , E1.SALARY 
     , E1.COMMISSION_PCT 
     , E1.MANAGER_ID 
     , E1.DEPARTMENT_ID 
     , E2.RNUM 
  FROM EMPLOYEES E1
 RIGHT OUTER JOIN (SELECT EMPLOYEE_ID
 						, RNUM 
 					 FROM (SELECT EMPLOYEE_ID 
								, ROWNUM AS RNUM
							 FROM (SELECT EMPLOYEE_ID 
							 		 FROM EMPLOYEES
							 	    ORDER BY SALARY ASC)
							WHERE ROWNUM <= 100)
					WHERE RNUM >= 90) E2
	ON E2.EMPLOYEE_ID = E1.EMPLOYEE_ID 
;
-- 129. 가장 적은 급여를 받는 사원의 상사명, 부서명을 조회한다.
SELECT EM.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN EMPLOYEES EM
 	ON E.MANAGER_ID = EM.EMPLOYEE_ID
 INNER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
 WHERE E.SALARY = (SELECT MIN(SALARY)
 					 FROM EMPLOYEES)
;
-- 130. 'PU_CLERK' 직무인 2번째 부터 5번째 사원의 부서명, 직무명을 조회한다.
SELECT JOB_TITLE 
  	 , DEPARTMENT_NAME 
  	 , RNUM
FROM (SELECT E.DEPARTMENT_ID 
		   , J.JOB_TITLE 
		   , D.DEPARTMENT_NAME 
 		   , ROWNUM AS RNUM
	    FROM EMPLOYEES E
	   INNER JOIN (SELECT DEPARTMENT_ID 
		      		    , DEPARTMENT_NAME 
	  	             FROM DEPARTMENTS) D
		  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
	   INNER JOIN (SELECT JOB_ID 
	 				    , JOB_TITLE 
	 			     FROM JOBS) J
	 	  ON E.JOB_ID = J.JOB_ID
	   WHERE E.JOB_ID = 'PU_CLERK'
	     AND ROWNUM <= 5)
 WHERE RNUM >= 2
;
-- 131. 월별 최대급여 중 2번째 부터 4번째 데이터만 조회한다.
SELECT SALARY
	 , RNUM
  FROM (SELECT SALARY 
  			 , ROWNUM AS RNUM
		  FROM (SELECT SALARY
				  FROM EMPLOYEES
				 ORDER BY SALARY DESC)
		 WHERE ROWNUM <= 4)
 WHERE RNUM >= 2
;
-- 132. 근무중인 사원이 가장 많은 도시와 사원의 수를 조회한다.
SELECT CITY
	 , CNT
  FROM (SELECT L.CITY 
			 , COUNT(E.EMPLOYEE_ID) AS CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 INNER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID 
		 GROUP BY L.CITY
		 ORDER BY CNT DESC)
 WHERE ROWNUM = 1
;
-- 133. 사원의 수가 가장 많은 부서명, 사원의 수를 조회한다.
SELECT DEPARTMENT_NAME
	 , CNT
  FROM (SELECT D.DEPARTMENT_NAME 
			 , COUNT(E.EMPLOYEE_ID) AS CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 GROUP BY D.DEPARTMENT_NAME 
		 ORDER BY CNT DESC)
 WHERE ROWNUM = 1
;
-- 134. 가장 많은 부서가 있는 도시를 조회한다.
SELECT CITY
	 , CNT
  FROM (SELECT L.CITY 
			 , COUNT(D.DEPARTMENT_ID) AS CNT 
		  FROM DEPARTMENTS D
		 INNER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID
		 GROUP BY L.CITY 
		 ORDER BY CNT DESC)
 WHERE ROWNUM = 1
;
-- 135. 가장 많은 사원이 있는 부서의 국가명을 조회한다.
SELECT C.COUNTRY_NAME 
  FROM COUNTRIES C
 INNER JOIN LOCATIONS L
 	ON C.COUNTRY_ID = L.COUNTRY_ID
 INNER JOIN DEPARTMENTS D
 	ON L.LOCATION_ID = D.LOCATION_ID
 WHERE D.DEPARTMENT_ID = (SELECT DEPARTMENT_ID
							FROM (SELECT D.DEPARTMENT_ID
									   , COUNT(E.EMPLOYEE_ID) AS CNT
									FROM EMPLOYEES E
								   INNER JOIN DEPARTMENTS D
									  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
								   GROUP BY D.DEPARTMENT_ID 
								   ORDER BY CNT DESC)
						   WHERE ROWNUM = 1)
;
-- 136. 'Europe' 에서 가장 많은 사원들이 있는 부서명을 조회한다.
SELECT DEPARTMENT_NAME
  FROM (SELECT D.DEPARTMENT_NAME 
			 , COUNT(E.EMPLOYEE_ID) AS CNT
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
		 INNER JOIN LOCATIONS L
		 	ON D.LOCATION_ID = L.LOCATION_ID
		 INNER JOIN COUNTRIES C
		 	ON L.COUNTRY_ID = C.COUNTRY_ID
		 WHERE C.REGION_ID = (SELECT REGION_ID 
		 						FROM REGIONS
		 					   WHERE REGION_NAME = 'Europe')
		 GROUP BY D.DEPARTMENT_NAME 
		 ORDER BY CNT DESC)
 WHERE ROWNUM = 1 
;
-- 137. 100번 사원의 모든 부하직원을 계층조회한다. 단, LEVEL이 4인 사원은 제외한다.
 SELECT EMPLOYEE_ID
      , FIRST_NAME 
      , LAST_NAME 
      , EMAIL 
      , PHONE_NUMBER 
      , HIRE_DATE 
      , JOB_ID 
      , SALARY 
      , COMMISSION_PCT 
      , MANAGER_ID 
      , DEPARTMENT_ID 
	  , LEVEL
   FROM EMPLOYEES
  WHERE LEVEL != 4
  START WITH EMPLOYEE_ID = 100
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
;
-- 138. 101번 사원의 모든 부하직원 들의 이름, 성, 상사사원번호, 상사사원명을 계층 조회한다.
-- SELECT E1.FIRST_NAME 
--      , E1.LAST_NAME 
--      , E1.MANAGER_ID 
----      , E2.EMPLOYEE_ID 
----      , E2.FIRST_NAME 
--	  , LEVEL
--   FROM EMPLOYEES E1
----  INNER JOIN EMPLOYEES E2
--  START WITH EMPLOYEE_ID = 101
--CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
--;
-- 139. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호, 상사사원명을 계층 조회한다.
-- SELECT EMPLOYEE_ID 
-- 	  , FIRST_NAME 
--      , LAST_NAME 
--      , MANAGER_ID 
--	  , LEVEL
--   FROM EMPLOYEES
--  START WITH EMPLOYEE_ID = 114
--CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
--;
-- 140. 114번 직원의 모든 상사들의 이름, 성, 상사사원번호, 상사사원명을 역순으로 계층 조회한다.
-- SELECT EMPLOYEE_ID 
-- 	  , FIRST_NAME 
--      , LAST_NAME 
--      , MANAGER_ID 
----	  , LEVEL
--   FROM EMPLOYEES 
--  START WITH EMPLOYEE_ID = 114
--CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
--  ORDER BY LEVEL DESC
--;
-- 141. 부서별 사원의 수를 조인을 이용해 다음과 같이 조회한다."부서명 (사원의 수)"
--SELECT DISTINCT D.DEPARTMENT_NAME || ' (' || CNT_D.CNT || ')'
--  FROM EMPLOYEES E
-- INNER JOIN DEPARTMENTS D
-- 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
-- INNER JOIN (SELECT DEPARTMENT_ID 
-- 				  , COUNT(EMPLOYEE_ID) AS CNT
-- 			   FROM EMPLOYEES 
-- 			  GROUP BY DEPARTMENT_ID) CNT_D
-- 	ON D.DEPARTMENT_ID = CNT_D.DEPARTMENT_ID 
--;
SELECT *
  FROM DEPARTMENTS D
 INNER JOIN (SELECT COUNT(E.DEPARTMENT_ID)
 			   FROM EMPLOYEES E
 			  WHERE )
;
-- 142. 부서별 사원의 수를 스칼라쿼리를 이용해 다음과 같이 조회한다. "부서명 (사원의 수)"
SELECT DISTINCT (SELECT D.DEPARTMENT_NAME 
				   FROM DEPARTMENTS D
				  WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
	|| ' ('
	|| (SELECT COUNT(EMPLOYEE_ID)
 		  FROM EMPLOYEES ED
 		 GROUP BY DEPARTMENT_ID
 	    HAVING ED.DEPARTMENT_ID = E.DEPARTMENT_ID)
 	|| ')'
  FROM EMPLOYEES E
;
-- 143. 사원의 정보를 다음과 같이 조회한다. "사원번호 번 사원의 이름은 성이름 입니다."
SELECT EMPLOYEE_ID 
	|| ' 번 사원의 이름은 '
	|| FIRST_NAME 
	|| LAST_NAME 
	|| ' 입니다.'
  FROM EMPLOYEES
;
-- 144. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원번호 번 사원의 상사명은 상사명 입니다."
SELECT EMPLOYEE_ID 
	|| ' 번 사원의 상사명은 '
	|| (SELECT EM.FIRST_NAME
		  FROM EMPLOYEES EM
		 WHERE EM.EMPLOYEE_ID = E.MANAGER_ID)
	|| ' 입니다.'
  FROM EMPLOYEES E
;
-- 145. 사원의 정보를 조인을 이용해 다음고 같이 조회한다. "사원명 (직무명)"
SELECT E.FIRST_NAME 
	|| ' (' 
	|| J.JOB_TITLE 
	|| ')'
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID 
;
-- 146. 사원의 정보를 스칼라쿼리를 이용해 다음과 같이 조회한다. "사원명 (직무명)"
SELECT E.FIRST_NAME 
	|| ' (' 
	|| (SELECT J.JOB_TITLE 
		  FROM JOBS J
		 WHERE E.JOB_ID = J.JOB_ID)
	|| ')'
  FROM EMPLOYEES E
;
-- 147. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서명을 조회한다.
SELECT DEPARTMENT_NAME 
  FROM (SELECT D.DEPARTMENT_NAME 
			 , MAX(E.SALARY) - MIN(E.SALARY) AS SAL_DIFF  
		  FROM EMPLOYEES E
		 INNER JOIN DEPARTMENTS D
		 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
		 GROUP BY D.DEPARTMENT_NAME  
		 ORDER BY SAL_DIFF DESC)
 WHERE ROWNUM = 1
;
-- 148. 부서별 급여 차이(최고급여 - 최저급여)가 가장 큰 부서에서 근무하는 사원들의 직무명을 중복없이 조회한다.
SELECT DISTINCT J.JOB_TITLE 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
 WHERE E.DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
							FROM (SELECT D.DEPARTMENT_ID
									   , MAX(E.SALARY) - MIN(E.SALARY) AS SAL_DIFF  
									FROM EMPLOYEES E
								   INNER JOIN DEPARTMENTS D
									  ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
								   GROUP BY D.DEPARTMENT_ID
								   ORDER BY SAL_DIFF DESC)
						   WHERE ROWNUM = 1)
;
-- 149. 부하직원이 없는 사원의 모든 정보를 조회한다.
SELECT EMPLOYEE_ID
     , FIRST_NAME 
     , LAST_NAME 
     , EMAIL 
     , PHONE_NUMBER 
     , HIRE_DATE 
     , JOB_ID 
     , SALARY 
     , COMMISSION_PCT 
     , MANAGER_ID 
     , DEPARTMENT_ID 
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID NOT IN (SELECT DISTINCT MANAGER_ID 
						     FROM EMPLOYEES
							WHERE MANAGER_ID IS NOT NULL)
;
-- 150. 사원번호가 100번인 사원의 사원번호, 이름과 사원번호로 내림차순 정렬된 사원의 사원번호, 이름 조회한다.

/*조회 예
--------------------
100    Steven
206    William
205    Shelley
204    Hermann
203    Susan
202    Pat
201    Michael
200    Jennifer
199    Douglas
198    Donald
197    Kevin
196    Alana
...
*/
-- 151. 모든 사원들의 이름과 부서번호, 부서명을 조회한다. 근무중인 부서가 없는 경우도 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_ID 
	 , D.DEPARTMENT_NAME 
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
;
-- 152. 모든 사원들의 이름과 부서번호, 부서명, 근무중인 도시를 조회한다. 근무중인 부서가 없거나 근무중인 도시가 없는 경우도 조회한다.
SELECT E.FIRST_NAME 
	 , D.DEPARTMENT_NAME 
	 , L.CITY 
  FROM EMPLOYEES E
  LEFT OUTER JOIN DEPARTMENTS D
 	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT OUTER JOIN LOCATIONS L
 	ON D.LOCATION_ID = L.LOCATION_ID
;
-- 153. 부서별로 근무중인 사원의 수를 조회한다. 근무중인 사원이 없는 부서는 0으로 조회한다.
SELECT D.DEPARTMENT_NAME 
	 , COUNT(E.EMPLOYEE_ID)
  FROM DEPARTMENTS D
  LEFT OUTER JOIN EMPLOYEES E
 	ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
 GROUP BY D.DEPARTMENT_NAME 
;
-- 154. 도시별로 존재하는 부서의 수를 조회한다. 존재하는 부서가 없는 도시는 0으로 조회한다.
SELECT L.CITY 
	 , COUNT(D.DEPARTMENT_ID)
  FROM LOCATIONS L
  LEFT JOIN DEPARTMENTS D
 	ON L.LOCATION_ID = D.LOCATION_ID 
 GROUP BY L.CITY 
;
-- 155. 도시별로 근무주인 사원의 수를 조회한다. 근무중인 사원이 없는 도시는 0으로 조회한다.
SELECT L.CITY 
	 , COUNT(E.EMPLOYEE_ID)
  FROM LOCATIONS L
  LEFT OUTER JOIN DEPARTMENTS D
 	ON L.LOCATION_ID = D.LOCATION_ID
  LEFT OUTER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 GROUP BY L.CITY 
;
-- 156. 모든 사원의 정보와 직무 변경이력을 함께 조회한다. 직무변경이력이 없는 사원도 함께 조회한다.
SELECT *
  FROM EMPLOYEES E
  LEFT OUTER JOIN JOB_HISTORY JH
 	ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID 
;
-- 157. 모든 사원의 현재 수행중인 직무명, 현재 근무중인 부서명, 이전에 수행한 직무명, 이전에 근무한 부서명을 조회한다.
--     과거 직무와 이전 부서명이 없는 사원도 함께 조회한다.
SELECT J.JOB_TITLE 
	 , D.DEPARTMENT_NAME 
	 , JH_T.JOB_TITLE 
	 , JH_T.DEPARTMENT_NAME 
  FROM EMPLOYEES E
 INNER JOIN JOBS J
 	ON E.JOB_ID = J.JOB_ID
  LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  LEFT OUTER JOIN (SELECT JH.EMPLOYEE_ID 
  						, J2.JOB_TITLE 
  						, D2.DEPARTMENT_NAME 
  					 FROM JOB_HISTORY JH
  					INNER JOIN JOBS J2
  					   ON JH.JOB_ID = J2.JOB_ID
  					 LEFT OUTER JOIN DEPARTMENTS D2
  					   ON JH.DEPARTMENT_ID = D2.DEPARTMENT_ID) JH_T
 	ON E.EMPLOYEE_ID = JH_T.EMPLOYEE_ID 
;